const fs=require('fs');const path=require('path');const crypto=require('crypto');
const {createConfig}=require('./config');const {createLogger}=require('./logger');const {Auth}=require('./auth');const {ModelManager}=require('./models/manager');const {MemoryManager}=require('./memory/manager');const {ContextEngine}=require('./context/engine');const {SkillManager}=require('./skills/manager');const {ToolRegistry}=require('./tools/registry');const {WebSearch}=require('./tools/web-search');const {WorkspaceManager,detectLanguage}=require('./workspace/manager');const {AgentLoop}=require('./agent/loop');const {MCPClient}=require('./mcp/client');const {DiscordStorage}=require('./discord');const {ResponseCache}=require('./cache');const {MultiAgent}=require('./agent/multi');const {Updater}=require('./updater');const {EvolutionEngine}=require('./evolution');const {questions}=require('./context/focus');const {normalize}=require('./context/normalizer');const {parseTags,stripTags}=require('./context/tags');
class VessieServer{
 constructor({root,app,express}){this.root=root;this.app=app;this.express=express;this.config=createConfig(root);this.logger=createLogger(root);this.auth=new Auth(this.config);this.models=new ModelManager(this.config,this.logger);this.memory=new MemoryManager(this.config,this.logger);this.context=new ContextEngine(this.config,this.logger);this.skills=new SkillManager(this.config,this.logger);this.tools=new ToolRegistry(this.config,this.logger);this.web=new WebSearch(this.config,this.logger);this.workspace=new WorkspaceManager(this.config,this.logger);this.mcp=new MCPClient(this.config,this.logger);this.discord=new DiscordStorage(this.config,this.logger);this.cache=new ResponseCache();this.multi=new MultiAgent(this.models,this.context,this.logger);this.evolution=new EvolutionEngine(this.config,this.skills,this.context,this.logger);this.updater=new Updater(this.config,this.logger);this.agent=new AgentLoop({config:this.config,logger:this.logger,modelManager:this.models,context:this.context,memory:this.memory,tools:this.tools,web:this.web,skills:this.skills});this.configure();}
 configure(){const a=this.app;a.disable('x-powered-by');if(this.config.trustProxy)a.set('trust proxy',1);a.use(this.express.json({limit:'2mb'}));a.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(),microphone=(),geolocation=()');if(this.config.corsOrigin!=='false')res.setHeader('Access-Control-Allow-Origin',this.config.corsOrigin);res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next();});
  const publicDir=path.join(this.root,'public');a.use(this.express.static(publicDir,{index:'index.html'}));
  const guard=(req,res,next)=>{if(req.path==='/auth/login'||req.path==='/health')return next();const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'')||req.headers['x-vessie-session'];if(!this.auth.check(token))return res.status(401).json({error:'Não autenticado'});req.sessionToken=token;next();};a.use('/api',guard);
  a.post('/api/auth/login',(req,res)=>{const r=this.auth.login(req.body?.password);if(!r.ok)return res.status(401).json({error:'Senha inválida'});res.json({ok:true,token:r.token});});
  a.post('/api/auth/logout',(req,res)=>{const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');this.auth.logout(token);res.json({ok:true});});
  a.get('/api/health',(req,res)=>res.json({ok:true,name:'VessieAI',version:'2.0.0',auth:this.config.authEnabled}));
  a.get('/api/status',async(req,res)=>res.json({name:'VessieAI',version:'2.1.0',model:this.config.lmModel,providerPreference:this.config.providerPreference,runtime:this.models.status(),lmStudioUrl:this.config.lmStudioUrl,agentLoop:this.config.agentLoopEnabled,adaptiveSystemPrompt:this.config.adaptiveSystemPrompt,webSearch:this.config.webSearchEnabled,memory:this.config.memoryEnabled,tools:this.tools.list(),skills:this.skills.list(),mcp:this.mcp.list()}));
  a.get('/api/runtime',(req,res)=>res.json(this.models.status()));
  a.post('/api/runtime/reload',async(req,res)=>{try{res.json(await this.models.init());}catch(e){res.status(502).json({error:e.message});}});
  a.get('/api/models',async(req,res)=>{try{res.json({models:await this.models.list(),configured:this.config.lmModels,current:this.config.lmModel});}catch(e){res.status(500).json({error:e.message});}});
  a.get('/api/config',(req,res)=>res.json({port:this.config.port,host:this.config.host,lmStudioUrl:this.config.lmStudioUrl,lmModel:this.config.lmModel,lmModels:this.config.lmModels,maxTokens:this.config.maxTokens,temperature:this.config.temperature,adaptiveSystemPrompt:this.config.adaptiveSystemPrompt,webSearchEnabled:this.config.webSearchEnabled,agentLoopEnabled:this.config.agentLoopEnabled,forceAllModule:this.config.forceAllModule,autoEvolutionEnabled:this.config.autoEvolutionEnabled,thinkMode:this.config.thinkMode}));
  a.get('/api/memory',(req,res)=>res.json(this.memory.data));a.delete('/api/memory',(req,res)=>{this.memory.clear();res.json({ok:true});});
  a.get('/api/context',(req,res)=>res.json(this.context.bundle(this.memory)));
  a.get('/api/focus/questions',(req,res)=>res.json({questions}));
  a.post('/api/focus/check',(req,res)=>{const text=String(req.body.input||'');const missing=[];if(!/(criar|fazer|implementar|corrigir|gerar|modificar)/i.test(text))missing.push('resultado');if(!/(node|python|javascript|typescript|html|css|java|c#|csharp|rust|go)/i.test(text))missing.push('linguagem');res.json({needsQuestionnaire:missing.length>0,missing});});
  a.get('/api/tags',(req,res)=>res.json({tags:['Think','Code','Interpretagem']}));
  a.get('/api/skills',(req,res)=>res.json({skills:this.skills.list()}));a.get('/api/skills/:name',(req,res)=>{const s=this.skills.get(req.params.name);if(!s)return res.status(404).json({error:'Skill não encontrada'});res.json(s);});
  a.post('/api/skills',(req,res)=>{try{const name=this.skills.create(req.body.name,req.body.content,req.body.meta);res.json({ok:true,name});}catch(e){res.status(400).json({error:e.message});}});
  a.post('/api/evolution/skill',async(req,res)=>{try{res.json({ok:true,name:await this.evolution.createSkill(req.body.description)});}catch(e){res.status(400).json({error:e.message});}});
  a.post('/api/multi-agent',async(req,res)=>{try{res.json(await this.multi.run(String(req.body.input||''),req.body.models||[]));}catch(e){res.status(502).json({error:e.message});}});
  a.get('/api/tools',(req,res)=>res.json({tools:this.tools.list()}));a.post('/api/tools/run',async(req,res)=>{try{res.json({result:await this.tools.run(req.body.name,req.body.args)});}catch(e){res.status(400).json({error:e.message});}});
  a.post('/api/web-search',async(req,res)=>{try{res.json({results:await this.web.search(req.body.query,Math.min(Number(req.body.maxResults)||this.config.webSearchMaxResults,10))});}catch(e){res.status(400).json({error:e.message});}});
  a.get('/api/mcp',(req,res)=>res.json({servers:this.mcp.list()}));
  a.post('/api/project/select',(req,res)=>{try{res.json(this.workspace.select(req.sessionToken,req.body.path,req.body.mode||'readwrite'));}catch(e){res.status(400).json({error:e.message});}});
  a.get('/api/project',(req,res)=>res.json(this.workspace.get(req.sessionToken)||{}));
  a.get('/api/project/files',(req,res)=>{try{res.json({files:this.workspace.list(req.sessionToken,req.query.dir||'.')});}catch(e){res.status(400).json({error:e.message});}});
  a.get('/api/project/file', (req,res)=>{try{res.json(this.workspace.read(req.sessionToken,req.query.path));}catch(e){res.status(400).json({error:e.message});}});
  a.put('/api/project/file',(req,res)=>{try{res.json(this.workspace.write(req.sessionToken,req.body.path,req.body.content,req.body.expectedHash));}catch(e){res.status(400).json({error:e.message});}});
  a.post('/api/project/patch',(req,res)=>{try{res.json(this.workspace.patch(req.sessionToken,req.body.path,req.body.patch));}catch(e){res.status(400).json({error:e.message});}});
  a.post('/api/agent/run',async(req,res)=>{const input=String(req.body.input||'').trim();if(!input)return res.status(400).json({error:'input obrigatório'});const result=await this.agent.run(input,{model:req.body.model||this.config.lmModel,sessionId:req.sessionToken});this.memory.ingest(input);if(result.success)this.memory.ingest(result.answer);if(this.config.discordEnabled)await this.discord.save(result.answer,'VessieAI result');res.json(result);});
  a.post('/api/chat',async(req,res)=>{const input=normalize(String(req.body.message||'')).trim();if(!input)return res.status(400).json({error:'Mensagem vazia'});const model=req.body.model||this.config.lmModel;const cacheKey={model,input};const cached=this.cache.get(cacheKey);if(cached)return res.json({...cached,cached:true});let answer;try{if(this.config.agentLoopEnabled){const r=await this.agent.run(input,{model,sessionId:req.sessionToken});answer=r.answer;this.memory.ingest(input);this.memory.ingest(answer);const payload={answer,trace:r.trace};this.cache.set(cacheKey,payload);return res.json(payload);}const context=this.context.bundle(this.memory);const messages=[{role:'system',content:`${this.config.systemPrompt}\n\nContexto:\n${JSON.stringify(context)}`},{role:'user',content:input}];answer=await this.models.chat(messages,{model});this.memory.ingest(input);this.memory.ingest(answer);const payload={answer,trace:[]};this.cache.set(cacheKey,payload);res.json(payload);}catch(e){res.status(502).json({error:e.message});}});
  a.post('/api/chat/stream',async(req,res)=>{const input=normalize(String(req.body.message||'')).trim();if(!input)return res.status(400).end();res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache');res.setHeader('Connection','keep-alive');try{const context=this.context.bundle(this.memory);const messages=[{role:'system',content:`${this.config.systemPrompt}\nContexto:${JSON.stringify(context)}`},{role:'user',content:input}];let answer='';for await(const chunk of this.models.stream(messages,{model:req.body.model||this.config.lmModel})){answer+=chunk;res.write(`data: ${JSON.stringify({content:chunk})}\n\n`);}this.memory.ingest(input);this.memory.ingest(answer);res.write(`data: ${JSON.stringify({done:true})}\n\n`);res.end();}catch(e){res.write(`data: ${JSON.stringify({error:e.message})}\n\n`);res.end();}});
  a.use((req,res,next)=>{ if(req.path.startsWith('/api/')) return res.status(404).json({error:'Rota não encontrada'}); res.sendFile(path.join(publicDir,'index.html')); });
 }
 async start(){this.logger.info(`VessieAI iniciando em ${this.config.host}:${this.config.port}`);this.app.listen(this.config.port,this.config.host,()=>this.logger.info('Servidor HTTP pronto'));}
}
module.exports={VessieServer};
