import { useMemo, useRef, useState } from 'react'
import { Blocks, Check, ChevronDown, Download, GripVertical, Play, Plus, RefreshCw, Save, Search, Settings2, Trash2, Upload, WandSparkles, X, Undo2, Redo2, AlertTriangle } from 'lucide-react'
import { blockCatalog, compileScratch, defaultScratch, exportScratch, importScratch, loadScratch, makeBlock, runScratch, saveScratch } from '../scratch/engine.js'

export default function ScratchStudio({ onCoreSync }) {
  const importInput = useRef(null)
  const [scratch, setScratch] = useState(loadScratch)
  const [history, setHistory] = useState([])
  const [future, setFuture] = useState([])
  const [selected, setSelected] = useState(null)
  const [query, setQuery] = useState('')
  const [customOpen, setCustomOpen] = useState(false)
  const [custom, setCustom] = useState({ label: '', value: '', color: '#d7e8e2' })
  const [run, setRun] = useState(null)
  const [saved, setSaved] = useState(false)
  const [dragged, setDragged] = useState(null)
  const selectedBlock = scratch.blocks.find((block) => block.id === selected)
  const filtered = useMemo(() => blockCatalog.filter((block) => `${block.label} ${block.type}`.toLowerCase().includes(query.toLowerCase())), [query])
  const update = (patch) => setScratch((current) => { const next = { ...current, ...patch }; setHistory((items) => [...items.slice(-19), current]); setFuture([]); return next })
  const undo = () => setHistory((items) => { const previous = items.at(-1); if (!previous) return items; setFuture((itemsFuture) => [scratch, ...itemsFuture].slice(0, 20)); setScratch(previous); return items.slice(0, -1) })
  const redo = () => setFuture((items) => { const next = items[0]; if (!next) return items; setHistory((itemsHistory) => [...itemsHistory, scratch].slice(-20)); setScratch(next); return items.slice(1) })
  function add(type) { const block = makeBlock(type); update({ blocks: [...scratch.blocks, block] }); setSelected(block.id) }
  function patchBlock(id, patch) { update({ blocks: scratch.blocks.map((block) => block.id === id ? { ...block, ...patch } : block) }) }
  function remove(id) { update({ blocks: scratch.blocks.filter((block) => block.id !== id) }); if (selected === id) setSelected(null) }
  function drop(targetId) { if (!dragged || dragged === targetId) return; const blocks = [...scratch.blocks]; const from = blocks.findIndex((block) => block.id === dragged); const to = blocks.findIndex((block) => block.id === targetId); const [item] = blocks.splice(from, 1); blocks.splice(to, 0, item); update({ blocks }); setDragged(null) }
  function createCustom() { if (!custom.label.trim()) return; const item = { type: `custom-${Date.now()}`, color: custom.color, label: custom.label, fields: [{ key: 'value', label: 'configuração', placeholder: custom.value || 'descreva o comportamento' }] }; const block = makeBlock('custom', { type: item.type, label: item.label, color: item.color, value: custom.value }); update({ customBlocks: [...scratch.customBlocks, item], blocks: [...scratch.blocks, block] }); setCustom({ label: '', value: '', color: '#d7e8e2' }); setCustomOpen(false); setSelected(block.id) }
  return <div className="scratch-studio">
    <div className="scratch-head"><div><div className="eyebrow">VESSIEAI / SCRATCH RUNTIME</div><h2>Monte seu sistema com blocos</h2><p>Crie personalidade, memória, agentes e automações que funcionam na máquina local ou offline no GitHub Pages.</p></div><div className="scratch-actions"><button className="secondary-button" onClick={() => importInput.current?.click()}><Upload size={15} />Importar</button><button className="secondary-button" onClick={() => exportScratch(scratch)}><Download size={15} />Exportar</button><button className="primary-button" onClick={() => { saveScratch(scratch); setSaved(true); setTimeout(() => setSaved(false), 1600) }}><Save size={15} />{saved ? 'Salvo' : 'Salvar'}</button></div></div>
    <input ref={importInput} type="file" accept="application/json,.scratch.json" hidden onChange={(event) => importScratch(event.target.files[0], (value) => value && setScratch(value))} />
    <div className="scratch-toolbar"><input value={scratch.name} onChange={(event) => update({ name: event.target.value })} aria-label="Nome do sistema" /><span className="toolbar-divider" /><button className="ghost-button" onClick={() => setScratch(defaultScratch())}><RefreshCw size={15} />Novo sistema</button><button className="ghost-button" onClick={undo} disabled={!history.length} title="Desfazer"><Undo2 size={15} /></button><button className="ghost-button" onClick={redo} disabled={!future.length} title="Refazer"><Redo2 size={15} /></button><button className="ghost-button" onClick={() => onCoreSync?.(scratch)}><RefreshCw size={15} />Sincronizar Core</button><span className="scratch-status"><span className="status-dot" />Local-first</span></div>
    <div className="scratch-grid">
      <aside className="block-library"><div className="library-head"><div><span className="eyebrow">BIBLIOTECA</span><h3>Blocos</h3></div><button className="icon-button" onClick={() => setCustomOpen(true)} title="Criar bloco customizado"><Plus size={17} /></button></div><label className="search-box"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar blocos" /></label><div className="library-list">{filtered.map((block) => <button key={block.type} className="library-block" style={{ '--block-color': block.color }} onClick={() => add(block.type)}><span className="block-shape"><Plus size={14} /></span><span><b>{block.label}</b><small>{block.type === 'custom' ? 'crie seu próprio comportamento' : 'bloco do sistema'}</small></span></button>)}<button className="custom-library" onClick={() => setCustomOpen(true)}><WandSparkles size={16} /><span><b>Criar bloco customizado</b><small>Descreva e configure seu bloco</small></span></button></div></aside>
      <section className="scratch-stage"><div className="stage-head"><div><span className="eyebrow">PALCO DE PROGRAMAÇÃO</span><h3>{scratch.name}</h3></div><span className="stage-count">{scratch.blocks.length} blocos</span></div><div className="stage-canvas"><div className="stack-guide" />{scratch.blocks.map((block, index) => <article key={block.id} draggable onDragStart={() => setDragged(block.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => drop(block.id)} onClick={() => setSelected(block.id)} className={`scratch-block ${selected === block.id ? 'selected' : ''} ${block.enabled === false ? 'disabled' : ''}`} style={{ '--block-color': block.color }}><div className="block-notch" /><div className="drag-handle"><GripVertical size={15} /></div><div className="block-content"><span className="block-type">{index + 1} · {block.type}</span><b>{block.label}</b><span>{block.value || 'Clique para configurar'}</span></div><button className="block-delete" onClick={(event) => { event.stopPropagation(); remove(block.id) }}><Trash2 size={14} /></button></article>)}{scratch.blocks.length === 0 && <div className="stage-empty"><Blocks size={31} /><b>Arraste ou adicione um bloco</b><span>Seu sistema começa no primeiro bloco.</span></div>}</div><div className="stage-footer"><button className="primary-button" onClick={() => setRun(runScratch(scratch))}><Play size={15} />Executar offline</button><code>{compileScratch(scratch).split('\n').length} linhas compiladas</code></div></section>
      <aside className="block-inspector"><div className="inspector-head"><div><span className="eyebrow">INSPECTOR</span><h3>Configuração</h3></div><Settings2 size={17} /></div>{selectedBlock ? <div className="inspector-form"><div className="inspector-chip" style={{ background: selectedBlock.color }}>{selectedBlock.type}</div><label>Nome do bloco<input value={selectedBlock.label} onChange={(event) => patchBlock(selectedBlock.id, { label: event.target.value })} /></label><label>Instrução ou valor<textarea value={selectedBlock.value} onChange={(event) => patchBlock(selectedBlock.id, { value: event.target.value })} /></label><label className="toggle-line"><span>Bloco ativo</span><input type="checkbox" checked={selectedBlock.enabled !== false} onChange={(event) => patchBlock(selectedBlock.id, { enabled: event.target.checked })} /></label><button className="danger-button" onClick={() => remove(selectedBlock.id)}><Trash2 size={14} />Excluir bloco</button></div> : <div className="inspector-empty"><Settings2 size={25} /><b>Selecione um bloco</b><span>O inspector permite personalizar cada etapa do seu sistema.</span></div>}</aside>
    </div>
    {run && <div className="run-console"><div><span className="eyebrow">EXECUÇÃO OFFLINE</span><button className="icon-button" onClick={() => setRun(null)}><X size={15} /></button></div>{!run.validation?.valid && <div className="run-warning"><AlertTriangle size={14} />{run.validation?.errors?.join(' ')}</div>}<pre>{run.output}</pre></div>}
    {customOpen && <div className="modal-backdrop" onClick={() => setCustomOpen(false)}><div className="custom-modal" onClick={(event) => event.stopPropagation()}><div className="inspector-head"><div><span className="eyebrow">NOVO COMPONENTE</span><h3>Criar bloco customizado</h3></div><button className="icon-button" onClick={() => setCustomOpen(false)}><X size={16} /></button></div><p>Descreva o comportamento que você quer transformar em um bloco reutilizável.</p><label>Nome do bloco<input autoFocus value={custom.label} onChange={(event) => setCustom({ ...custom, label: event.target.value })} placeholder="Ex: Revisar resposta" /></label><label>Comportamento<textarea value={custom.value} onChange={(event) => setCustom({ ...custom, value: event.target.value })} placeholder="Ex: verifique fatos e responda com uma fonte" /></label><label>Cor do bloco<input type="color" value={custom.color} onChange={(event) => setCustom({ ...custom, color: event.target.value })} /></label><button className="primary-button" onClick={createCustom}><WandSparkles size={15} />Criar bloco</button></div></div>}
  </div>
}

