const fs=require('fs');const path=require('path');const crypto=require('crypto');const {safeJoin,ensureDir}=require('../utils/fs');
const ignored=new Set(['.git','node_modules','vessieai-core/node_modules','.env']);
function detectLanguage(file,content=''){const ext=path.extname(file).toLowerCase();const map={'.js':'javascript','.jsx':'javascript','.ts':'typescript','.tsx':'typescript','.py':'python','.html':'html','.css':'css','.json':'json','.md':'markdown','.java':'java','.cs':'csharp','.cpp':'cpp','.c':'c','.rs':'rust','.go':'go','.php':'php','.rb':'ruby','.sh':'shell','.bat':'batch'};if(map[ext])return map[ext];if(/^\s*<(!doctype|html)/i.test(content))return 'html';if(/\b(def|import)\b/.test(content))return 'python';return 'text';}
class WorkspaceManager{
 constructor(config,logger){this.config=config;this.logger=logger;this.selected=new Map();ensureDir(config.workspaceRoot);}
 select(session,dir,mode='readwrite'){const p=path.resolve(dir);const allowed=this.config.projectRoots.some(root=>p===root||p.startsWith(root+path.sep));if(!allowed)throw new Error('Projeto fora das raízes permitidas.');if(!fs.existsSync(p)||!fs.statSync(p).isDirectory())throw new Error('Pasta inválida.');this.selected.set(session,{path:p,mode});return {path:p,mode};}
 get(session){return this.selected.get(session)||null;}
 list(session,rel='.') {const s=this.get(session);if(!s)throw new Error('Nenhum projeto selecionado.');const p=safeJoin(s.path,rel);return fs.readdirSync(p,{withFileTypes:true}).filter(x=>!ignored.has(x.name)).map(x=>({name:x.name,type:x.isDirectory()?'dir':'file',language:x.isFile()?detectLanguage(x.name):null}));}
 read(session,rel){const s=this.get(session);if(!s)throw new Error('Nenhum projeto selecionado.');const p=safeJoin(s.path,rel);const st=fs.statSync(p);if(st.size>2*1024*1024)throw new Error('Arquivo >2MB não suportado.');const content=fs.readFileSync(p,'utf8');return {path:rel,language:detectLanguage(rel,content),content,sha256:crypto.createHash('sha256').update(content).digest('hex')};}
 write(session,rel,content,expectedHash){const s=this.get(session);if(!s)throw new Error('Nenhum projeto selecionado.');if(s.mode!=='readwrite')throw new Error('Projeto em modo somente leitura.');const p=safeJoin(s.path,rel);if(expectedHash && fs.existsSync(p)){const old=fs.readFileSync(p);const h=crypto.createHash('sha256').update(old).digest('hex');if(h!==expectedHash)throw new Error('Conflito: arquivo mudou desde a leitura.');}ensureDir(path.dirname(p));fs.writeFileSync(p,content,'utf8');return this.read(session,rel);}
 patch(session,rel,patchText){const current=this.read(session,rel);const lines=current.content.split(/\r?\n/);const ops=String(patchText).split(/\r?\n/).filter(Boolean);for(const op of ops){const m=op.match(/^(replace|insert|delete)\s+(\d+)(?:-(\d+))?\s*:\s*(.*)$/s);if(!m)continue;const a=Number(m[2])-1,b=Number(m[3]||m[2])-1; if(m[1]==='delete')lines.splice(a,b-a+1);else if(m[1]==='replace')lines.splice(a,b-a+1,m[4]);else lines.splice(a,0,m[4]);}return this.write(session,rel,lines.join('\n'),current.sha256);}
}
module.exports={WorkspaceManager,detectLanguage};
