import { useState } from 'react'
import { Activity, Brain, Code2, Database, Gauge, Layers3, MessageSquare, Save, Sparkles, WifiOff } from 'lucide-react'
import ScratchStudio from './components/ScratchStudio.jsx'
import { loadDB, saveDB } from './storage/db.js'

const nav = [{ id: 'overview', label: 'Visão geral', icon: Gauge }, { id: 'scratch', label: 'Scratch Studio', icon: Layers3 }, { id: 'memory', label: 'Memória local', icon: Database }, { id: 'code', label: 'Biblioteca de código', icon: Code2 }]

export default function App() {
  const [page, setPage] = useState('overview')
  const [saved, setSaved] = useState(false)
  const [coreStatus, setCoreStatus] = useState('Pronto para sincronizar')
  function save() { saveDB(loadDB()); setSaved(true); setTimeout(() => setSaved(false), 1600) }
  async function syncCore(scratch) { setCoreStatus('Sincronizando...'); try { const response = await fetch('http://localhost:4173/api/scratch', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(scratch) }); if (!response.ok) throw new Error(); setCoreStatus('Core local sincronizado') } catch { setCoreStatus('Modo Pages: salvo localmente') } }
  return <div className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={19} /></div><div><strong>VessieAI</strong><small>scratch runtime</small></div></div><div className="runtime"><span className="status-dot" />{coreStatus}<span className="runtime-divider" />{saved ? 'Alterações salvas' : 'GitHub Pages + máquina local'}</div><button className="save-button" onClick={save}><Save size={15} />Salvar</button></header><div className="app-layout"><aside className="rail"><div className="rail-title">WORKSPACE</div>{nav.map(({ id, label, icon: Icon }) => <button key={id} className={`nav-item ${page === id ? 'active' : ''}`} onClick={() => setPage(id)}><Icon size={17} /><span>{label}</span></button>)}<div className="rail-bottom"><div className="offline-card"><WifiOff size={16} /><strong>Offline-first</strong><span>O Scratch continua no navegador.</span></div><div className="core-mini"><Activity size={15} /><span>Core local opcional</span></div></div></aside><main className="main-content">{page === 'scratch' ? <ScratchStudio onCoreSync={syncCore} /> : <SimplePage page={page} goScratch={() => setPage('scratch')} />}</main></div></div>
}

function SimplePage({ page, goScratch }) { const content = { overview: { title: 'Visão geral', eyebrow: 'ESTÚDIO LOCAL', heading: 'Crie sistemas de IA com blocos.', text: 'O Scratch Studio conecta personalidade, memória, agentes e scripts em uma experiência visual que funciona na máquina local e no GitHub Pages.' }, memory: { title: 'Memória local', eyebrow: 'CONTEXTO PERSISTENTE', heading: 'O contexto da sua IA fica no dispositivo.', text: 'Guarde informações e use-as nos blocos sem depender de um banco remoto.' }, code: { title: 'Biblioteca de código', eyebrow: 'SCRIPTS E COMPONENTES', heading: 'Transforme blocos em automações.', text: 'Crie e exporte scripts a partir do sistema montado no Scratch Studio.' } }[page] || {}
  return <div className="page-content"><div className="page-heading"><div><div className="eyebrow">{content.eyebrow}</div><h1>{content.title}</h1><p>{content.text}</p></div></div><section className="hero-grid"><article className="hero-card"><div className="hero-icon"><Layers3 size={22} /></div><div className="eyebrow">WORKSPACE VISUAL</div><h2>{content.heading}</h2><p>Use blocos customizados, inspector, compilação e execução offline para construir sua própria IA brasileira.</p><button className="primary-button" onClick={goScratch}><Layers3 size={16} />Abrir Scratch Studio</button></article><article className="chat-card"><div className="card-head"><div><div className="eyebrow">RUNTIME</div><h3>Arquitetura híbrida</h3></div><MessageSquare size={18} /></div><div className="runtime-list"><div className="runtime-row"><span className="live-dot" /><b>GitHub Pages</b><small>Interface e dados locais</small></div><div className="runtime-row"><span className="live-dot" /><b>Máquina local</b><small>VessieAI-Core e modelos</small></div><div className="runtime-row"><span className="muted-dot" /><b>LM Studio / GGUF</b><small>Providers opcionais</small></div></div></article></section><div className="metric-grid"><div className="metric"><Brain size={18} /><span>Personalidade</span><strong>Scratch</strong></div><div className="metric"><Code2 size={18} /><span>Scripts</span><strong>Em lote</strong></div><div className="metric"><Database size={18} /><span>Memória</span><strong>Local</strong></div></div></div> }
